/**
 * `npm run schema`: writes the definitions JSON Schema generated by
 * src/harness/definitions/schema.ts to schema/puck.schema.json and the
 * starter Puck home (docs/examples/config-repo/). CI regenerates it and
 * fails on any diff, and test/unit/definitions-schema.test.ts compares the
 * committed copies too.
 *
 * The TypeScript sources load through a require hook that transpiles with
 * the project's own `typescript`, so this needs no build step or extra
 * dependency.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { createRequire } from 'node:module';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import ts from 'typescript';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');

/** Where the schema is committed, relative to the repo root. */
export const SCHEMA_OUTPUTS = ['schema/puck.schema.json', 'docs/examples/config-repo/puck.schema.json'];

const require = createRequire(import.meta.url);
require.extensions['.ts'] = (module, filename) => {
  const { outputText } = ts.transpileModule(readFileSync(filename, 'utf8'), {
    fileName: filename,
    compilerOptions: { module: ts.ModuleKind.CommonJS, target: ts.ScriptTarget.ES2021, esModuleInterop: true },
  });
  module._compile(outputText, filename);
};

const { schemaText } = require(join(root, 'src/harness/definitions/schema.ts'));
const text = schemaText();
for (const rel of SCHEMA_OUTPUTS) {
  writeFileSync(join(root, rel), text);
  console.log(`wrote ${rel}`);
}
